marp:
    marp --theme ./my-marp.css index.md -o docs/index.html

serve:
    BROWSER=/bin/true live-server --port=8000 --no-browser ./docs/

entr:
    echo 'index.md' 'my-marp.css' | to text | entr -c just marp

marp-pdf:
    marp --theme ./my-marp.css index.md --pdf

marp-serve-not-secure:
    PORT=8001 marp --theme ./my-marp.css -s . --allow-local-files -w

marp-publish:
    mkdir docs
    cp -r images docs/
    marp --theme ./my-marp.css -I . -o docs
