# cubrid-dev2-pr configuration
# DS - Distributed Systems
# SM - Storage Manager
teammates = [
  # "hgryoo", # DS
  "hornetmj", # Team Leader
  "vimkim", # SM
  # "H2SU", # DS
  "YeunjunLee", # SM
  # "youngjun9072", # DS
  "InChiJun", # SM
  "lht1199", # SM
]
reviewer = "vimkim" # whose "my review" state is shown
repo = "CUBRID/cubrid" # target repo
limit = 300 # gh pr list --limit
